#ifndef CONFIG_HPP
#define CONFIG_HPP

#define ATX_WIDTH 244
#define ATX_HEIGHT 305

#define MICROATX_WIDTH 234
#define MICROATX_HEIGHT 244

#define MINIITX_WIDTH 170
#define MINIITX_HEIGHT 170

#define PI                      3.14159265
#define ROTATE_VAL              3.14159265358979323846 / 16
#define EPS 1e-3

// #define SIZE_SC                 50
#define SIZE_SC                 3
#define BRICK_TOP_HEIGHT        10
#define BRICK_TOP_SIZE_SC       0.3

// #define PLATE_HEIGHT            20
#define PLATE_HEIGHT            10
#define BASE_Z                  8000
#define BASE_START              10, 10, BASE_Z

// #define X_CENTER                500
#define X_CENTER                720
// #define Y_CENTER                390
#define Y_CENTER                470

#define SCALE_VAL               0.1

#define LIGHT_X                 1000
#define LIGHT_Y                 1000

#define MOVE_VAL                50

#define BLACK_COLOR            0, 0, 0

#define SHADOW_VAL              30

#define BASE_COLOR              220, 220, 220
#define BASE_COLOR_SHADOW       220 - SHADOW_VAL, 220 - SHADOW_VAL, 220 - SHADOW_VAL

#define BRICK_COLOR             255, 051, 051
#define BRICK_COLOR_SHADOW      255 - SHADOW_VAL, 051 - SHADOW_VAL, 051 - SHADOW_VAL

#define PLATE_COLOR             153, 255, 051
#define PLATE_COLOR_SHADOW      153 - SHADOW_VAL, 255 - SHADOW_VAL, 051 - SHADOW_VAL

#define TILE_COLOR              051, 255, 255
#define TILE_COLOR_SHADOW       051 - SHADOW_VAL, 255 - SHADOW_VAL, 255 - SHADOW_VAL

#define ARC_COLOR               255, 051, 255
#define ARC_COLOR_SHADOW        255 - SHADOW_VAL, 051 - SHADOW_VAL, 255 - SHADOW_VAL

#define CYLINDER_COLOR          255, 255, 051
#define CYLINDER_COLOR_SHADOW   255 - SHADOW_VAL, 255 - SHADOW_VAL, 051 - SHADOW_VAL


/*
 * ======================= ATX CONFIG =======================
*/

// PERIPHERIA SOCKETS

// HDMI DP port
#define ATX_HDMI_DP_OFFSET_X 0
#define ATX_HDMI_DP_OFFSET_Y 18
#define ATX_HDMI_DP_WIDTH 18 * SIZE_SC
#define ATX_HDMI_DP_HEIGHT 22 * SIZE_SC
#define ATX_HDMI_DP_DEPTH 22 * SIZE_SC
#define WALL_DEPTH 2 * SIZE_SC

#define ATX_HDMI_DP_LEFTWALL_WIDTH ATX_HDMI_DP_WIDTH - WALL_DEPTH
#define ATX_HDMI_DP_LEFTWALL_HEIGHT WALL_DEPTH
#define ATX_HDMI_DP_LEFTWALL_DEPTH (11 * SIZE_SC) - WALL_DEPTH

#define ATX_HDMI_DP_RIGHTWALL_WIDTH ATX_HDMI_DP_WIDTH - WALL_DEPTH
#define ATX_HDMI_DP_RIGHTWALL_HEIGHT WALL_DEPTH
#define ATX_HDMI_DP_RIGHTWALL_DEPTH (11 * SIZE_SC) - WALL_DEPTH

#define ATX_HDMI_DP_BOTTOM_WIDTH ATX_HDMI_DP_WIDTH - WALL_DEPTH
#define ATX_HDMI_DP_BOTTOM_HEIGHT ATX_HDMI_DP_HEIGHT - (2 * WALL_DEPTH)
#define ATX_HDMI_DP_BOTTOM_DEPTH WALL_DEPTH

#define ATX_HDMI_DP_BACKWALL_WIDTH WALL_DEPTH
#define ATX_HDMI_DP_BACKWALL_HEIGHT ATX_HDMI_DP_HEIGHT
#define ATX_HDMI_DP_BACKWALL_DEPTH (11 * SIZE_SC) - WALL_DEPTH

#define ATX_HDMI_DP_TOP_WIDTH ATX_HDMI_DP_WIDTH
#define ATX_HDMI_DP_TOP_HEIGHT ATX_HDMI_DP_HEIGHT
#define ATX_HDMI_DP_TOP_DEPTH WALL_DEPTH

// BIOS flbk
#define ATX_BIOS_FLBK_OFFSET_X 0
#define ATX_BIOS_FLBK_OFFSET_Y 95
#define ATX_BIOS_FLBK_WIDTH 8 * SIZE_SC
#define ATX_BIOS_FLBK_HEIGHT 8 * SIZE_SC
#define ATX_BIOS_FLBK_DEPTH 8 * SIZE_SC

#define ATX_BIOS_FLBK_LEFTWALL_WIDTH ATX_BIOS_FLBK_WIDTH - WALL_DEPTH
#define ATX_BIOS_FLBK_LEFTWALL_HEIGHT WALL_DEPTH
#define ATX_BIOS_FLBK_LEFTWALL_DEPTH ATX_BIOS_FLBK_DEPTH - WALL_DEPTH

#define ATX_BIOS_FLBK_RIGHTWALL_WIDTH ATX_BIOS_FLBK_WIDTH - WALL_DEPTH
#define ATX_BIOS_FLBK_RIGHTWALL_HEIGHT WALL_DEPTH
#define ATX_BIOS_FLBK_RIGHTWALL_DEPTH ATX_BIOS_FLBK_DEPTH - WALL_DEPTH

#define ATX_BIOS_FLBK_BOTTOM_WIDTH ATX_BIOS_FLBK_WIDTH - WALL_DEPTH
#define ATX_BIOS_FLBK_BOTTOM_HEIGHT ATX_BIOS_FLBK_HEIGHT - (2 * WALL_DEPTH)
#define ATX_BIOS_FLBK_BOTTOM_DEPTH WALL_DEPTH

#define ATX_BIOS_FLBK_BACKWALL_WIDTH WALL_DEPTH
#define ATX_BIOS_FLBK_BACKWALL_HEIGHT ATX_BIOS_FLBK_HEIGHT
#define ATX_BIOS_FLBK_BACKWALL_DEPTH ATX_BIOS_FLBK_DEPTH - WALL_DEPTH

#define ATX_BIOS_FLBK_TOP_WIDTH ATX_BIOS_FLBK_WIDTH
#define ATX_BIOS_FLBK_TOP_HEIGHT ATX_BIOS_FLBK_HEIGHT
#define ATX_BIOS_FLBK_TOP_DEPTH WALL_DEPTH

// U32G2

#define ATX_U32G2_1_4_OFFSET_X 0
#define ATX_U32G2_1_4_OFFSET_Y 144
#define ATX_U32G2_1_4_WIDTH 24 * SIZE_SC
#define ATX_U32G2_1_4_HEIGHT 14 * SIZE_SC
#define ATX_U32G2_1_4_DEPTH 8 * SIZE_SC

#define ATX_U32G2_LEFTWALL_WIDTH ATX_U32G2_1_4_WIDTH - WALL_DEPTH
#define ATX_U32G2_LEFTWALL_HEIGHT WALL_DEPTH
#define ATX_U32G2_LEFTWALL_DEPTH ATX_U32G2_1_4_DEPTH - WALL_DEPTH

#define ATX_U32G2_RIGHTWALL_WIDTH ATX_U32G2_1_4_WIDTH - WALL_DEPTH
#define ATX_U32G2_RIGHTWALL_HEIGHT WALL_DEPTH
#define ATX_U32G2_RIGHTWALL_DEPTH ATX_U32G2_1_4_DEPTH - WALL_DEPTH

#define ATX_U32G2_BOTTOM_WIDTH ATX_U32G2_1_4_WIDTH - WALL_DEPTH
#define ATX_U32G2_BOTTOM_HEIGHT ATX_U32G2_1_4_HEIGHT - (2 * WALL_DEPTH)
#define ATX_U32G2_BOTTOM_DEPTH WALL_DEPTH

#define ATX_U32G2_BACKWALL_WIDTH WALL_DEPTH
#define ATX_U32G2_BACKWALL_HEIGHT ATX_U32G2_1_4_HEIGHT
#define ATX_U32G2_BACKWALL_DEPTH ATX_U32G2_1_4_DEPTH - WALL_DEPTH

#define ATX_U32G2_TOP_WIDTH ATX_U32G2_1_4_WIDTH
#define ATX_U32G2_TOP_HEIGHT ATX_U32G2_1_4_HEIGHT
#define ATX_U32G2_TOP_DEPTH WALL_DEPTH

// LAN

#define ATX_LAN2_U32G2_56_OFFSET_X 0
#define ATX_LAN2_U32G2_56_OFFSET_Y 66 * SIZE_SC

#define ATX_LAN_LEFTWALL_DEPTH 15 * SIZE_SC - WALL_DEPTH
#define ATX_LAN_RIGHTWALL_DEPTH 15 * SIZE_SC - WALL_DEPTH
#define ATX_LAN_BACKWALL_DEPTH 15 * SIZE_SC - WALL_DEPTH

#define ATX_U3252_C8_LAN1_U32G2_7_OFFSET_X 0
#define ATX_U3252_C8_LAN1_U32G2_7_OFFSET_Y 88 * SIZE_SC

// wifi

#define ATX_M2_WIFI_OFFSET_X 0
#define ATX_M2_WIFI_OFFSET_Y 108 * SIZE_SC

#define ATX_M2_WIFI_WIDTH 28 * SIZE_SC
#define ATX_M2_WIFI_HEIGHT 8 * SIZE_SC

#define ATX_M2_WIFI_LEFTWALL_WIDTH ATX_M2_WIFI_WIDTH - WALL_DEPTH
#define ATX_M2_WIFI_LEFTWALL_HEIGHT WALL_DEPTH
#define ATX_M2_WIFI_LEFTWALL_DEPTH (8 * SIZE_SC) - WALL_DEPTH

#define ATX_M2_WIFI_RIGHTWALL_WIDTH ATX_M2_WIFI_WIDTH - WALL_DEPTH
#define ATX_M2_WIFI_RIGHTWALL_HEIGHT WALL_DEPTH
#define ATX_M2_WIFI_RIGHTWALL_DEPTH (8 * SIZE_SC) - WALL_DEPTH

#define ATX_M2_WIFI_BOTTOM_WIDTH ATX_M2_WIFI_WIDTH - WALL_DEPTH
#define ATX_M2_WIFI_BOTTOM_HEIGHT ATX_M2_WIFI_HEIGHT - (2 * WALL_DEPTH)
#define ATX_M2_WIFI_BOTTOM_DEPTH WALL_DEPTH

#define ATX_M2_WIFI_TOP_WIDTH ATX_M2_WIFI_WIDTH
#define ATX_M2_WIFI_TOP_HEIGHT ATX_M2_WIFI_HEIGHT
#define ATX_M2_WIFI_TOP_DEPTH WALL_DEPTH

#define ATX_M2_WIFI_BACKWALL_WIDTH WALL_DEPTH
#define ATX_M2_WIFI_BACKWALL_HEIGHT ATX_M2_WIFI_HEIGHT
#define ATX_M2_WIFI_BACKWALL_DEPTH (8 * SIZE_SC) - WALL_DEPTH

#define ATX_M2_WIFI_SEP_WIDTH ATX_M2_WIFI_WIDTH
#define ATX_M2_WIFI_SEP_HEIGHT ATX_M2_WIFI_HEIGHT
#define ATX_M2_WIFI_SEP_DEPTH 22 * SIZE_SC


// audio
#define ATX_AUDIO_OFFSET_X 0
#define ATX_AUDIO_OFFSET_Y 124 * SIZE_SC
#define ATX_AUDIO_WIDTH 20 * SIZE_SC
#define ATX_AUDIO_HEIGHT 12 * SIZE_SC
#define ATX_AUDIO_DEPTH 12 * SIZE_SC

#define ATX_AUDIO_1_OFFSET_X ATX_AUDIO_OFFSET_X
#define ATX_AUDIO_1_OFFSET_Y ATX_AUDIO_OFFSET_Y

#define ATX_AUDIO_2_OFFSET_X ATX_AUDIO_OFFSET_X
#define ATX_AUDIO_2_OFFSET_Y ATX_AUDIO_OFFSET_Y + ATX_AUDIO_HEIGHT

#define ATX_AUDIO_3_OFFSET_X ATX_AUDIO_OFFSET_X
#define ATX_AUDIO_3_OFFSET_Y ATX_AUDIO_OFFSET_Y

#define ATX_AUDIO_4_OFFSET_X ATX_AUDIO_OFFSET_X
#define ATX_AUDIO_4_OFFSET_Y ATX_AUDIO_OFFSET_Y + ATX_AUDIO_HEIGHT

#define ATX_AUDIO_5_OFFSET_X ATX_AUDIO_OFFSET_X
#define ATX_AUDIO_5_OFFSET_Y ATX_AUDIO_OFFSET_Y

#define ATX_AUDIO_6_OFFSET_X ATX_AUDIO_OFFSET_X
#define ATX_AUDIO_6_OFFSET_Y ATX_AUDIO_OFFSET_Y + ATX_AUDIO_HEIGHT

#define ATX_AUDIO_LEFTWALL_WIDTH ATX_AUDIO_WIDTH - WALL_DEPTH
#define ATX_AUDIO_LEFTWALL_HEIGHT WALL_DEPTH
#define ATX_AUDIO_LEFTWALL_DEPTH ATX_AUDIO_DEPTH - WALL_DEPTH

#define ATX_AUDIO_RIGHTWALL_WIDTH ATX_AUDIO_WIDTH - WALL_DEPTH
#define ATX_AUDIO_RIGHTWALL_HEIGHT WALL_DEPTH
#define ATX_AUDIO_RIGHTWALL_DEPTH ATX_AUDIO_DEPTH - WALL_DEPTH

#define ATX_AUDIO_BACKWALL_WIDTH WALL_DEPTH
#define ATX_AUDIO_BACKWALL_HEIGHT ATX_AUDIO_HEIGHT
#define ATX_AUDIO_BACKWALL_DEPTH ATX_AUDIO_DEPTH - WALL_DEPTH

#define ATX_AUDIO_BOTTOM_WIDTH ATX_AUDIO_WIDTH - WALL_DEPTH
#define ATX_AUDIO_BOTTOM_HEIGHT ATX_AUDIO_HEIGHT - (2 * WALL_DEPTH)
#define ATX_AUDIO_BOTTOM_DEPTH WALL_DEPTH

#define ATX_AUDIO_TOP_WIDTH ATX_AUDIO_WIDTH
#define ATX_AUDIO_TOP_HEIGHT ATX_AUDIO_HEIGHT
#define ATX_AUDIO_TOP_DEPTH WALL_DEPTH


// CPU SOCKET
#define ATX_socketAM4_BASE_WIDTH 52 * SIZE_SC
#define ATX_socketAM4_BASE_HEIGHT 44 * SIZE_SC
#define ATX_socketAM4_BASE_DEPTH 5
#define ATX_socketAM4_FRAME_WIDTH 52 * SIZE_SC
#define ATX_socketAM4_FRAME_HEIGHT 44 * SIZE_SC
#define ATX_socketAM4_FRAME_DEPTH 7
#define ATX_socketAM4_LEFTFRAME_WIDTH 2 * SIZE_SC
#define ATX_socketAM4_RIGHTFRAME_WIDTH 6 * SIZE_SC
#define ATX_socketAM4_TOPFRAME_WIDTH 3 * SIZE_SC
#define ATX_socketAM4_BOTTOMFRAME_WIDTH 3 * SIZE_SC
#define ATX_socketAM4_OFFSET_X 114 * SIZE_SC
#define ATX_socketAM4_OFFSET_Y 70 * SIZE_SC

// RAM SOCKETS
#define ATX_DDR4_DIMM_WIDTH 24
#define ATX_DDR4_DIMM_HEIGHT 420
#define ATX_DDR4_DIMM_TOPFRAMEWIDTH 5
#define ATX_DDR4_DIMM_BOTTOMFRAMEWIDTH 5
#define ATX_DDR4_DIMM_LEFTFRAMEWIDTH 9
#define ATX_DDR4_DIMM_RIGHTFRAMEWIDTH 9

#define ATX_DDR4_DIMM_B1_OFFSET_X 546
#define ATX_DDR4_DIMM_B1_OFFSET_Y 66

#define ATX_DDR4_DIMM_B2_OFFSET_X 576
#define ATX_DDR4_DIMM_B2_OFFSET_Y 66

#define ATX_DDR4_DIMM_A1_OFFSET_X 606
#define ATX_DDR4_DIMM_A1_OFFSET_Y 66

#define ATX_DDR4_DIMM_A2_OFFSET_X 636
#define ATX_DDR4_DIMM_A2_OFFSET_Y 66

// GPU SOCKETS
#define ATX_PCIEX16_WIDTH 270
#define ATX_PCIEX16_HEIGHT 24
#define ATX_PCIEX16_TOPFRAMEWIDTH 9
#define ATX_PCIEX16_BOTTOMFRAMEWIDTH 9
#define ATX_PCIEX16_LEFTFRAMEWIDTH 5
#define ATX_PCIEX16_RIGHTFRAMEWIDTH 5

#define ATX_PCIEX16_1_OFFSET_X 126
#define ATX_PCIEX16_1_OFFSET_Y 528

#define ATX_PCIEX16_2_OFFSET_X 126
#define ATX_PCIEX16_2_OFFSET_Y 708

#define ATX_PCIEX16_3_OFFSET_X 126
#define ATX_PCIEX16_3_OFFSET_Y 828

#define ATX_C22110_1_RADIUS 4 * SIZE_SC
#define ATX_C22110_1_HEIGHT 20
#define ATX_C22110_1_SEGMENTS 10
#define ATX_C22110_1_OFFSET_X 40 * SIZE_SC
#define ATX_C22110_1_OFFSET_Y 166 * SIZE_SC

#define ATX_C2280_1_RADIUS 4 * SIZE_SC
#define ATX_C2280_1_HEIGHT 20
#define ATX_C2280_1_SEGMENTS 10
#define ATX_C2280_1_OFFSET_X 70 * SIZE_SC
#define ATX_C2280_1_OFFSET_Y 166 * SIZE_SC

#define ATX_C2260_1_RADIUS 4 * SIZE_SC
#define ATX_C2260_1_HEIGHT 20
#define ATX_C2260_1_SEGMENTS 10
#define ATX_C2260_1_OFFSET_X 92 * SIZE_SC
#define ATX_C2260_1_OFFSET_Y 166 * SIZE_SC

#define ATX_C2242_1_RADIUS 4 * SIZE_SC
#define ATX_C2242_1_HEIGHT 20
#define ATX_C2242_1_SEGMENTS 10
#define ATX_C2242_1_OFFSET_X 110 * SIZE_SC
#define ATX_C2242_1_OFFSET_Y 166 * SIZE_SC

#define ATX_C22110_2_RADIUS 4 * SIZE_SC
#define ATX_C22110_2_HEIGHT 20
#define ATX_C22110_2_SEGMENTS 10
#define ATX_C22110_2_OFFSET_X 100 * SIZE_SC
#define ATX_C22110_2_OFFSET_Y 260 * SIZE_SC

#define ATX_C2280_2_RADIUS 4 * SIZE_SC
#define ATX_C2280_2_HEIGHT 20
#define ATX_C2280_2_SEGMENTS 10
#define ATX_C2280_2_OFFSET_X 130 * SIZE_SC
#define ATX_C2280_2_OFFSET_Y 260 * SIZE_SC

#define ATX_C2260_2_RADIUS 4 * SIZE_SC
#define ATX_C2260_2_HEIGHT 20
#define ATX_C2260_2_SEGMENTS 10
#define ATX_C2260_2_OFFSET_X 150 * SIZE_SC
#define ATX_C2260_2_OFFSET_Y 260 * SIZE_SC

#define ATX_C2242_2_RADIUS 4 * SIZE_SC
#define ATX_C2242_2_HEIGHT 20
#define ATX_C2242_2_SEGMENTS 10
#define ATX_C2242_2_OFFSET_X 170 * SIZE_SC
#define ATX_C2242_2_OFFSET_Y 260 * SIZE_SC

#define ATX_BATTERY_RADIUS 10 * SIZE_SC
#define ATX_BATTERY_HEIGHT 5
#define ATX_BATTERY_SEGMENTS 10
#define ATX_BATTERY_OFFSET_X 70 * SIZE_SC
#define ATX_BATTERY_OFFSET_Y 210 * SIZE_SC

#define ATX_AMDX570_WIDTH 26 * SIZE_SC
#define ATX_AMDX570_HEIGHT 26 * SIZE_SC
#define ATX_AMDX570_DEPTH 5
#define ATX_AMDX570_OFFSET_X 164 * SIZE_SC
#define ATX_AMDX570_OFFSET_Y 210 * SIZE_SC

// sata
#define ATX_SATA6G_1_2_BASE_OFFSET_X 690
#define ATX_SATA6G_1_2_BASE_OFFSET_Y 214 * SIZE_SC

#define ATX_SATA6G_3_4_BASE_OFFSET_X 690
#define ATX_SATA6G_3_4_BASE_OFFSET_Y 214 * SIZE_SC + ATX_SATA6G_BACKWALL_HEIGHT

#define ATX_SATA6G_5_6_BASE_OFFSET_X 690
#define ATX_SATA6G_5_6_BASE_OFFSET_Y (214 * SIZE_SC) + (2 * ATX_SATA6G_BACKWALL_HEIGHT)

#define ATX_SATA6G_7_8_BASE_OFFSET_X 690
#define ATX_SATA6G_7_8_BASE_OFFSET_Y (214 * SIZE_SC) + (3 * ATX_SATA6G_BACKWALL_HEIGHT)

#define ATX_SATA6G_BOTTOM_WIDTH (14 * SIZE_SC) - (2 * SIZE_SC)
#define ATX_SATA6G_BOTTOM_HEIGHT 17 * SIZE_SC
#define ATX_SATA6G_BOTTOM_DEPTH 2 * SIZE_SC

#define ATX_SATA6G_RIGHTWALL_WIDTH 14 * SIZE_SC - (2 * SIZE_SC)
#define ATX_SATA6G_RIGHTWALL_HEIGHT 2 * SIZE_SC
#define ATX_SATA6G_RIGHTWALL_DEPTH 7 * SIZE_SC - ATX_SATA6G_BOTTOM_DEPTH

#define ATX_SATA6G_LEFTWALL_WIDTH (14 * SIZE_SC) - (2 * SIZE_SC)
#define ATX_SATA6G_LEFTWALL_HEIGHT 2 * SIZE_SC
#define ATX_SATA6G_LEFTWALL_DEPTH 7 * SIZE_SC - ATX_SATA6G_BOTTOM_DEPTH

#define ATX_SATA6G_BACKWALL_WIDTH 2 * SIZE_SC
#define ATX_SATA6G_BACKWALL_HEIGHT 17 * SIZE_SC
#define ATX_SATA6G_BACKWALL_DEPTH 7 * SIZE_SC - ATX_SATA6G_BOTTOM_DEPTH

#define ATX_SATA6G_TOP_WIDTH ATX_SATA6G_BACKWALL_WIDTH + ATX_SATA6G_BOTTOM_WIDTH
#define ATX_SATA6G_TOP_HEIGHT 17 * SIZE_SC
#define ATX_SATA6G_TOP_DEPTH 2 * SIZE_SC

// SuperIO
#define ATX_SuperIO_OFFSET_X 12 * SIZE_SC
#define ATX_SuperIO_OFFSET_Y 216 * SIZE_SC
#define ATX_SuperIO_WIDTH 16 * SIZE_SC
#define ATX_SuperIO_HEIGHT 16 * SIZE_SC
#define ATX_SuperIO_DEPTH 4

// IntelI22AT
#define ATX_IntelI22AT_OFFSET_X 16 * SIZE_SC
#define ATX_IntelI22AT_OFFSET_Y 186 * SIZE_SC
#define ATX_IntelI22AT_WIDTH 8 * SIZE_SC
#define ATX_IntelI22AT_HEIGHT 8 * SIZE_SC
#define ATX_IntelI22AT_DEPTH 4

// EATX ports
#define ATX_EATX12V_1_OFFSET_X 50 * SIZE_SC
#define ATX_EATX12V_1_OFFSET_Y 2 * SIZE_SC
#define ATX_EATX12V_1_WIDTH 20 * SIZE_SC
#define ATX_EATX12V_1_HEIGHT 8 * SIZE_SC
#define ATX_EATX12V_1_DEPTH 1 * SIZE_SC
#define ATX_EATX12V_1_FRAME_DEPTH 10 * SIZE_SC
#define ATX_EATX12V_1_FRAME_WIDTH 5

#define ATX_EATX12V_2_OFFSET_X 40 * SIZE_SC
#define ATX_EATX12V_2_OFFSET_Y 2 * SIZE_SC
#define ATX_EATX12V_2_WIDTH 8 * SIZE_SC
#define ATX_EATX12V_2_HEIGHT 8 * SIZE_SC
#define ATX_EATX12V_2_DEPTH 1 * SIZE_SC
#define ATX_EATX12V_2_FRAME_DEPTH 10 * SIZE_SC
#define ATX_EATX12V_2_FRAME_WIDTH 5

#define ATX_EATXPWR_OFFSET_X 230 * SIZE_SC
#define ATX_EATXPWR_OFFSET_Y 80 * SIZE_SC
#define ATX_EATXPWR_WIDTH 8 * SIZE_SC
#define ATX_EATXPWR_HEIGHT 50 * SIZE_SC
#define ATX_EATXPWR_DEPTH 1 * SIZE_SC
#define ATX_EATXPWR_FRAME_DEPTH 10 * SIZE_SC
#define ATX_EATXPWR_FRAME_WIDTH 5

// RTL8125_CG
#define ATX_RTL8125_CG_OFFSET_X 52 * SIZE_SC
#define ATX_RTL8125_CG_OFFSET_Y 156 * SIZE_SC
#define ATX_RTL8125_CG_WIDTH 10 * SIZE_SC
#define ATX_RTL8125_CG_HEIGHT 10 * SIZE_SC
#define ATX_RTL8125_CG_DEPTH 4

// NODE
#define ATX_NODE_OFFSET_X 72 * SIZE_SC
#define ATX_NODE_OFFSET_Y 292 * SIZE_SC
#define ATX_NODE_WIDTH 16 * SIZE_SC
#define ATX_NODE_HEIGHT 8 * SIZE_SC
#define ATX_NODE_DEPTH 1 * SIZE_SC
#define ATX_NODE_FRAME_DEPTH 10 * SIZE_SC
#define ATX_NODE_FRAME_WIDTH 5

// USB34
#define ATX_USB34_OFFSET_X 96 * SIZE_SC
#define ATX_USB34_OFFSET_Y 292 * SIZE_SC
#define ATX_USB34_WIDTH 16 * SIZE_SC
#define ATX_USB34_HEIGHT 8 * SIZE_SC
#define ATX_USB34_DEPTH 1 * SIZE_SC
#define ATX_USB34_FRAME_DEPTH 10 * SIZE_SC
#define ATX_USB34_FRAME_WIDTH 5

// USB12
#define ATX_USB12_OFFSET_X 118 * SIZE_SC
#define ATX_USB12_OFFSET_Y 292 * SIZE_SC
#define ATX_USB12_WIDTH 16 * SIZE_SC
#define ATX_USB12_HEIGHT 8 * SIZE_SC
#define ATX_USB12_DEPTH 1 * SIZE_SC
#define ATX_USB12_FRAME_DEPTH 10 * SIZE_SC
#define ATX_USB12_FRAME_WIDTH 5

// U32G1_1011
#define ATX_U32G1_1011_OFFSET_X 136 * SIZE_SC
#define ATX_U32G1_1011_OFFSET_Y 292 * SIZE_SC
#define ATX_U32G1_1011_WIDTH 24 * SIZE_SC
#define ATX_U32G1_1011_HEIGHT 8 * SIZE_SC
#define ATX_U32G1_1011_DEPTH 1 * SIZE_SC
#define ATX_U32G1_1011_FRAME_DEPTH 10 * SIZE_SC
#define ATX_U32G1_1011_FRAME_WIDTH 5

// BIOS
#define ATX_BIOS_OFFSET_X 68 * SIZE_SC
#define ATX_BIOS_OFFSET_Y 136 * SIZE_SC
#define ATX_BIOS_WIDTH 3 * SIZE_SC
#define ATX_BIOS_HEIGHT 6 * SIZE_SC
#define ATX_BIOS_DEPTH 1 * SIZE_SC
#define ATX_BIOS_FRAME_DEPTH 7 * SIZE_SC
#define ATX_BIOS_FRAME_WIDTH 3

// SPI_TPM
#define ATX_SPI_TPM_OFFSET_X 84 * SIZE_SC
#define ATX_SPI_TPM_OFFSET_Y 138 * SIZE_SC
#define ATX_SPI_TPM_WIDTH 4 * SIZE_SC
#define ATX_SPI_TPM_HEIGHT 16 * SIZE_SC
#define ATX_SPI_TPM_DEPTH 1 * SIZE_SC
#define ATX_SPI_TPM_FRAME_DEPTH 7 * SIZE_SC
#define ATX_SPI_TPM_FRAME_WIDTH 3


/*
 * ======================= MICRO-ATX CONFIG =======================
*/

// PERIPHERIA
#define MICROATX_HDMI1_DP_OFFSET_X 0
#define MICROATX_HDMI1_DP_OFFSET_Y 18
#define MICROATX_HDMI1_DP_WIDTH 48
#define MICROATX_HDMI1_DP_HEIGHT 54

#define MICROATX_HDMI2_OFFSET_X 0
#define MICROATX_HDMI2_OFFSET_Y 90
#define MICROATX_HDMI2_WIDTH 42
#define MICROATX_HDMI2_HEIGHT 48

#define MICROATX_KBMS_USB_E34_OFFSET_X 0
#define MICROATX_KBMS_USB_E34_OFFSET_Y 162
#define MICROATX_KBMS_USB_E34_WIDTH 60
#define MICROATX_KBMS_USB_E34_HEIGHT 48

#define MICROATX_U32G2_C2_OFFSET_X 0
#define MICROATX_U32G2_C2_OFFSET_Y 228
#define MICROATX_U32G2_C2_WIDTH 48
#define MICROATX_U32G2_C2_HEIGHT 48

#define MICROATX_LAN_USB_E12_OFFSET_X 0
#define MICROATX_LAN_USB_E12_OFFSET_Y 294
#define MICROATX_LAN_USB_E12_WIDTH 84
#define MICROATX_LAN_USB_E12_HEIGHT 54

// AUDIO

#define MICROATX_AUDIO_OFFSET_X 0
#define MICROATX_AUDIO_OFFSET_Y 142 * SIZE_SC

// Processor slot
#define MICROATX_LGA1200_OFFSET_X 270
#define MICROATX_LGA1200_OFFSET_Y 174
#define MICROATX_LGA1200_BASE_WIDTH 44 * SIZE_SC
#define MICROATX_LGA1200_BASE_HEIGHT 52 * SIZE_SC
#define MICROATX_LGA1200_BASE_DEPTH 5

#define MICROATX_LGA1200_FRAME_WIDTH 44 * SIZE_SC
#define MICROATX_LGA1200_FRAME_HEIGHT 52 * SIZE_SC
#define MICROATX_LGA1200_FRAME_DEPTH 7
#define MICROATX_LGA1200_TOPFRAME_WIDTH 6 * SIZE_SC
#define MICROATX_LGA1200_BOTTOMFRAME_WIDTH 2 * SIZE_SC
#define MICROATX_LGA1200_LEFTFRAME_WIDTH 3 * SIZE_SC
#define MICROATX_LGA1200_RIGHTFRAME_WIDTH 3 * SIZE_SC

// RAM
#define MICROATX_DDR4_DIMM_WIDTH 24
#define MICROATX_DDR4_DIMM_HEIGHT 420
#define MICROATX_DDR4_DIMM_TOPFRAMEWIDTH 5
#define MICROATX_DDR4_DIMM_BOTTOMFRAMEWIDTH 5
#define MICROATX_DDR4_DIMM_LEFTFRAMEWIDTH 9
#define MICROATX_DDR4_DIMM_RIGHTFRAMEWIDTH 9

#define MICROATX_DDR4_DIMM_A1_OFFSET_X 498
#define MICROATX_DDR4_DIMM_A1_OFFSET_Y 42

#define MICROATX_DDR4_DIMM_A2_OFFSET_X 528
#define MICROATX_DDR4_DIMM_A2_OFFSET_Y 42

#define MICROATX_DDR4_DIMM_B1_OFFSET_X 558
#define MICROATX_DDR4_DIMM_B1_OFFSET_Y 42

#define MICROATX_DDR4_DIMM_B2_OFFSET_X 588
#define MICROATX_DDR4_DIMM_B2_OFFSET_Y 42

// GPU
#define MICROATX_PCIEX16_WIDTH 270
#define MICROATX_PCIEX16_HEIGHT 24
#define MICROATX_PCIEX16_TOPFRAMEWIDTH 9
#define MICROATX_PCIEX16_BOTTOMFRAMEWIDTH 9
#define MICROATX_PCIEX16_LEFTFRAMEWIDTH 5
#define MICROATX_PCIEX16_RIGHTFRAMEWIDTH 5


#define MICROATX_PCIEX16_1_OFFSET_X 126
#define MICROATX_PCIEX16_1_OFFSET_Y 474

#define MICROATX_PCIEX16_2_OFFSET_X 126
#define MICROATX_PCIEX16_2_OFFSET_Y 660

// capacitors
#define MICROATX_C2242_1_RADIUS 4 * SIZE_SC
#define MICROATX_C2242_1_HEIGHT 20
#define MICROATX_C2242_1_SEGMENTS 10
#define MICROATX_C2242_1_OFFSET_X 90 * SIZE_SC
#define MICROATX_C2242_1_OFFSET_Y 140 * SIZE_SC

#define MICROATX_C2260_1_RADIUS 4 * SIZE_SC
#define MICROATX_C2260_1_HEIGHT 20
#define MICROATX_C2260_1_SEGMENTS 10
#define MICROATX_C2260_1_OFFSET_X 110 * SIZE_SC
#define MICROATX_C2260_1_OFFSET_Y 140 * SIZE_SC

#define MICROATX_C2280_1_RADIUS 4 * SIZE_SC
#define MICROATX_C2280_1_HEIGHT 20
#define MICROATX_C2280_1_SEGMENTS 10
#define MICROATX_C2280_1_OFFSET_X 130 * SIZE_SC
#define MICROATX_C2280_1_OFFSET_Y 140 * SIZE_SC

#define MICROATX_C2242_2_RADIUS 4 * SIZE_SC
#define MICROATX_C2242_2_HEIGHT 20
#define MICROATX_C2242_2_SEGMENTS 10
#define MICROATX_C2242_2_OFFSET_X 40 * SIZE_SC
#define MICROATX_C2242_2_OFFSET_Y 180 * SIZE_SC

#define MICROATX_C2260_2_RADIUS 4 * SIZE_SC
#define MICROATX_C2260_2_HEIGHT 20
#define MICROATX_C2260_2_SEGMENTS 10
#define MICROATX_C2260_2_OFFSET_X 60 * SIZE_SC
#define MICROATX_C2260_2_OFFSET_Y 180 * SIZE_SC

#define MICROATX_C2280_2_RADIUS 4 * SIZE_SC
#define MICROATX_C2280_2_HEIGHT 20
#define MICROATX_C2280_2_SEGMENTS 10
#define MICROATX_C2280_2_OFFSET_X 80 * SIZE_SC
#define MICROATX_C2280_2_OFFSET_Y 180 * SIZE_SC

#define MICROATX_BATTERY_RADIUS 10 * SIZE_SC
#define MICROATX_BATTERY_HEIGHT 5
#define MICROATX_BATTERY_SEGMENTS 10
#define MICROATX_BATTERY_OFFSET_X 20 * SIZE_SC
#define MICROATX_BATTERY_OFFSET_Y 180 * SIZE_SC

// sata
#define MICROATX_SATA6G_1_2_BASE_OFFSET_X 660
#define MICROATX_SATA6G_1_2_BASE_OFFSET_Y 190 * SIZE_SC

#define MICROATX_SATA6G_3_4_BASE_OFFSET_X 660
#define MICROATX_SATA6G_3_4_BASE_OFFSET_Y 190 * SIZE_SC + ATX_SATA6G_BACKWALL_HEIGHT

// ATXPWR
#define MICROATX_ATXPWR_OFFSET_X 224 * SIZE_SC
#define MICROATX_ATXPWR_OFFSET_Y 36 * SIZE_SC
#define MICROATX_ATXPWR_WIDTH 8 * SIZE_SC
#define MICROATX_ATXPWR_HEIGHT 50 * SIZE_SC
#define MICROATX_ATXPWR_DEPTH 1 * SIZE_SC
#define MICROATX_ATXPWR_FRAME_DEPTH 10 * SIZE_SC
#define MICROATX_ATXPWR_FRAME_WIDTH 5

// IntelB560
#define MICROATX_IntelB560_OFFSET_X 158 * SIZE_SC
#define MICROATX_IntelB560_OFFSET_Y 188 * SIZE_SC
#define MICROATX_IntelB560_WIDTH 24 * SIZE_SC
#define MICROATX_IntelB560_HEIGHT 24 * SIZE_SC
#define MICROATX_IntelB560_DEPTH 4

#define MICROATX_SuperIO_OFFSET_X 78 * SIZE_SC
#define MICROATX_SuperIO_OFFSET_Y 200 * SIZE_SC
#define MICROATX_SuperIO_WIDTH 16 * SIZE_SC
#define MICROATX_SuperIO_HEIGHT 16 * SIZE_SC
#define MICROATX_SuperIO_DEPTH 4

// U32G1_34
#define MICROATX_U32G1_34_OFFSET_X 224 * SIZE_SC
#define MICROATX_U32G1_34_OFFSET_Y 94 * SIZE_SC
#define MICROATX_U32G1_34_WIDTH 8 * SIZE_SC
#define MICROATX_U32G1_34_HEIGHT 24 * SIZE_SC
#define MICROATX_U32G1_34_DEPTH 1 * SIZE_SC
#define MICROATX_U32G1_34_FRAME_DEPTH 10 * SIZE_SC
#define MICROATX_U32G1_34_FRAME_WIDTH 5

// U32G1_56
#define MICROATX_U32G1_56_OFFSET_X 224 * SIZE_SC
#define MICROATX_U32G1_56_OFFSET_Y 126 * SIZE_SC
#define MICROATX_U32G1_56_WIDTH 8 * SIZE_SC
#define MICROATX_U32G1_56_HEIGHT 24 * SIZE_SC
#define MICROATX_U32G1_56_DEPTH 1 * SIZE_SC
#define MICROATX_U32G1_56_FRAME_DEPTH 10 * SIZE_SC
#define MICROATX_U32G1_56_FRAME_WIDTH 5

// ATX_12V
#define MICROATX_ATX_12V_OFFSET_X 50 * SIZE_SC
#define MICROATX_ATX_12V_OFFSET_Y 4 * SIZE_SC
#define MICROATX_ATX_12V_WIDTH 20 * SIZE_SC
#define MICROATX_ATX_12V_HEIGHT 8 * SIZE_SC
#define MICROATX_ATX_12V_DEPTH 1 * SIZE_SC
#define MICROATX_ATX_12V_FRAME_DEPTH 10 * SIZE_SC
#define MICROATX_ATX_12V_FRAME_WIDTH 5

// M2_1
#define MICROATX_M2_1_OFFSET_X 48 * SIZE_SC
#define MICROATX_M2_1_OFFSET_Y 132 * SIZE_SC
#define MICROATX_M2_1_WIDTH 8 * SIZE_SC
#define MICROATX_M2_1_HEIGHT 20 * SIZE_SC
#define MICROATX_M2_1_DEPTH 1 * SIZE_SC
#define MICROATX_M2_1_FRAME_DEPTH 2 * SIZE_SC
#define MICROATX_M2_1_FRAME_WIDTH 3

// LPT
#define MICROATX_LPT_OFFSET_X 54 * SIZE_SC
#define MICROATX_LPT_OFFSET_Y 236 * SIZE_SC
#define MICROATX_LPT_WIDTH 34 * SIZE_SC
#define MICROATX_LPT_HEIGHT 6 * SIZE_SC
#define MICROATX_LPT_DEPTH 1 * SIZE_SC
#define MICROATX_LPT_FRAME_DEPTH 2 * SIZE_SC
#define MICROATX_LPT_FRAME_WIDTH 3

// CHAFAN2
#define MICROATX_CHAFAN2_OFFSET_X 90 * SIZE_SC
#define MICROATX_CHAFAN2_OFFSET_Y 234 * SIZE_SC
#define MICROATX_CHAFAN2_WIDTH 20 * SIZE_SC
#define MICROATX_CHAFAN2_HEIGHT 8 * SIZE_SC
#define MICROATX_CHAFAN2_DEPTH 1 * SIZE_SC
#define MICROATX_CHAFAN2_FRAME_DEPTH 2 * SIZE_SC
#define MICROATX_CHAFAN2_FRAME_WIDTH 3

// BIOS
#define MICROATX_BIOS_OFFSET_X 186 * SIZE_SC
#define MICROATX_BIOS_OFFSET_Y 220 * SIZE_SC
#define MICROATX_BIOS_WIDTH 3 * SIZE_SC
#define MICROATX_BIOS_HEIGHT 6 * SIZE_SC
#define MICROATX_BIOS_DEPTH 1 * SIZE_SC
#define MICROATX_BIOS_FRAME_DEPTH 7 * SIZE_SC
#define MICROATX_BIOS_FRAME_WIDTH 3

/*
 * ======================= MINI-ITX CONFIG =======================
*/

// PERIPHERIA
#define MINIITX_USB3_5_OFFSET_X 0
#define MINIITX_USB3_5_OFFSET_Y 54
#define MINIITX_USB3_5_WIDTH 48
#define MINIITX_USB3_5_HEIGHT 42

#define MINIITX_USB7_10_OFFSET_X 0
#define MINIITX_USB7_10_OFFSET_Y 108
#define MINIITX_USB7_10_WIDTH 72
#define MINIITX_USB7_10_HEIGHT 48

#define MINIITX_HDMI_DP_OFFSET_X 0
#define MINIITX_HDMI_DP_OFFSET_Y 166
#define MINIITX_HDMI_DP_WIDTH 54
#define MINIITX_HDMI_DP_HEIGHT 66

#define MINIITX_LAN_USB3_34_OFFSET_X 0
#define MINIITX_LAN_USB3_34_OFFSET_Y 241
#define MINIITX_LAN_USB3_34_WIDTH 72
#define MINIITX_LAN_USB3_34_HEIGHT 54

#define MINIITX_M2_WIFI_OFFSET_X 0
#define MINIITX_M2_WIFI_OFFSET_Y 306
#define MINIITX_M2_WIFI_WIDTH 90
#define MINIITX_M2_WIFI_HEIGHT 24

// AUDIO

#define MINIITX_AUDIO_OFFSET_X 0
#define MINIITX_AUDIO_OFFSET_Y 134 * SIZE_SC

#define MINIITX_AUDIO_1_OFFSET_X MINIITX_AUDIO_OFFSET_X
#define MINIITX_AUDIO_1_OFFSET_Y MINIITX_AUDIO_OFFSET_Y

#define MINIITX_AUDIO_2_OFFSET_X MINIITX_AUDIO_OFFSET_X
#define MINIITX_AUDIO_2_OFFSET_Y MINIITX_AUDIO_OFFSET_Y + ATX_AUDIO_HEIGHT

#define MINIITX_AUDIO_3_OFFSET_X MINIITX_AUDIO_OFFSET_X
#define MINIITX_AUDIO_3_OFFSET_Y MINIITX_AUDIO_OFFSET_Y

#define MINIITX_AUDIO_4_OFFSET_X MINIITX_AUDIO_OFFSET_X
#define MINIITX_AUDIO_4_OFFSET_Y MINIITX_AUDIO_OFFSET_Y + ATX_AUDIO_HEIGHT

#define MINIITX_AUDIO_5_OFFSET_X MINIITX_AUDIO_OFFSET_X
#define MINIITX_AUDIO_5_OFFSET_Y MINIITX_AUDIO_OFFSET_Y

#define MINIITX_AUDIO_6_OFFSET_X MINIITX_AUDIO_OFFSET_X
#define MINIITX_AUDIO_6_OFFSET_Y MINIITX_AUDIO_OFFSET_Y + ATX_AUDIO_HEIGHT

// RAM
#define MINIITX_DDR4_DIMM_WIDTH 24
#define MINIITX_DDR4_DIMM_HEIGHT 420
#define MINIITX_DDR4_DIMM_TOPFRAMEWIDTH 5
#define MINIITX_DDR4_DIMM_BOTTOMFRAMEWIDTH 5
#define MINIITX_DDR4_DIMM_LEFTFRAMEWIDTH 9
#define MINIITX_DDR4_DIMM_RIGHTFRAMEWIDTH 9

#define MINIITX_DDR4_DIMM_A1_OFFSET_X 414
#define MINIITX_DDR4_DIMM_A1_OFFSET_Y 24

#define MINIITX_DDR4_DIMM_B1_OFFSET_X 444
#define MINIITX_DDR4_DIMM_B1_OFFSET_Y 24

// GPU
#define MINIITX_PCIEX16_WIDTH 270
#define MINIITX_PCIEX16_HEIGHT 24
#define MINIITX_PCIEX16_TOPFRAMEWIDTH 9
#define MINIITX_PCIEX16_BOTTOMFRAMEWIDTH 9
#define MINIITX_PCIEX16_LEFTFRAMEWIDTH 5
#define MINIITX_PCIEX16_RIGHTFRAMEWIDTH 5

#define MINIITX_PCIEX16_1_OFFSET_X 126
#define MINIITX_PCIEX16_1_OFFSET_Y 474

// capacitors
#define MINIITX_C2280_RADIUS 4 * SIZE_SC
#define MINIITX_C2280_HEIGHT 20
#define MINIITX_C2280_SEGMENTS 10
#define MINIITX_C2280_OFFSET_X 40 * SIZE_SC
#define MINIITX_C2280_OFFSET_Y 130 * SIZE_SC

#define MINIITX_C2260_RADIUS 4 * SIZE_SC
#define MINIITX_C2260_HEIGHT 20
#define MINIITX_C2260_SEGMENTS 10
#define MINIITX_C2260_OFFSET_X 60 * SIZE_SC
#define MINIITX_C2260_OFFSET_Y 130 * SIZE_SC

#define MINIITX_SATA6G_1_OFFSET_X 120 * SIZE_SC
#define MINIITX_SATA6G_1_OFFSET_Y 110 * SIZE_SC

#define MINIITX_SATA6G_2_OFFSET_X 120 * SIZE_SC
#define MINIITX_SATA6G_2_OFFSET_Y 130 * SIZE_SC

#define MINIITX_SATA6G_3_OFFSET_X 160 * SIZE_SC
#define MINIITX_SATA6G_3_OFFSET_Y 90 * SIZE_SC

#define MINIITX_SATA6G_4_OFFSET_X 160 * SIZE_SC
#define MINIITX_SATA6G_4_OFFSET_Y 110 * SIZE_SC

#define MINIITX_SATA6G_BASE_WIDTH ATX_SATA6G_RIGHTWALL_DEPTH + ATX_SATA6G_TOP_DEPTH
#define MINIITX_SATA6G_BASE_HEIGHT ATX_SATA6G_BACKWALL_HEIGHT
#define MINIITX_SATA6G_BASE_DEPTH 1

#define MINIITX_SATA6G_FRAME_WIDTH ATX_SATA6G_RIGHTWALL_DEPTH + ATX_SATA6G_TOP_DEPTH
#define MINIITX_SATA6G_FRAME_HEIGHT ATX_SATA6G_TOP_HEIGHT
#define MINIITX_SATA6G_FRAME_DEPTH ATX_SATA6G_TOP_WIDTH
#define MINIITX_SATA6G_LEFTFRAME_WIDTH 2 * SIZE_SC
#define MINIITX_SATA6G_RIGHTFRAME_WIDTH 2 * SIZE_SC
#define MINIITX_SATA6G_TOPFRAME_WIDTH 2 * SIZE_SC
#define MINIITX_SATA6G_BOTTOMFRAME_WIDTH 2 * SIZE_SC

/*
 * ======================= RAM 4GB DIMENSIONS =======================
*/
#define RAM_4GB_DEPTH 30 * SIZE_SC
#define RAM_4GB_WIDTH 6
#define RAM_4GB_HEIGHT 410

#define RAM_4GB_ACC_DEPTH 35
#define RAM_4GB_ACC_WIDTH 2
#define RAM_4GB_ACC_HEIGHT 40

/*
 * ======================= RAM 8GB DIMENSIONS =======================
*/
#define RAM_8GB_DEPTH 30 * SIZE_SC
#define RAM_8GB_WIDTH 6
#define RAM_8GB_HEIGHT 410

#define RAM_8GB_ACC_DEPTH 35
#define RAM_8GB_ACC_WIDTH 2
#define RAM_8GB_ACC_HEIGHT 40


/*
 * ======================= RAM 16GB DIMENSIONS =======================
*/
#define RAM_16GB_DEPTH 30 * SIZE_SC
#define RAM_16GB_WIDTH 6
#define RAM_16GB_HEIGHT 410

#define RAM_16GB_ACC_DEPTH 35
#define RAM_16GB_ACC_WIDTH 2
#define RAM_16GB_ACC_HEIGHT 170

/*
 * ======================= RAM 32GB DIMENSIONS =======================
*/
#define RAM_32GB_DEPTH 30 * SIZE_SC
#define RAM_32GB_WIDTH 6
#define RAM_32GB_HEIGHT 410

#define RAM_32GB_ACC_DEPTH 35
#define RAM_32GB_ACC_WIDTH 2
#define RAM_32GB_ACC_HEIGHT 360



/*
 * ======================= GPU 4GB DIMENSIONS =======================
*/
#define GPU_4GB_DEPTH 20 * SIZE_SC
#define GPU_4GB_WIDTH 260
#define GPU_4GB_HEIGHT 6

#define GPU_4GB_BOARD_DEPTH 72 * SIZE_SC
#define GPU_4GB_BOARD_HEIGHT 6
#define GPU_4GB_BOARD_WIDTH 150 * SIZE_SC

#define GPU_4GB_CHIPSET_ACC_DEPTH 28 * SIZE_SC
#define GPU_4GB_CHIPSET_ACC_WIDTH 24 * SIZE_SC
#define GPU_4GB_CHIPSET_ACC_HEIGHT 6

#define GPU_4GB_MEMBLOCK_ACC_DEPTH 20 * SIZE_SC
#define GPU_4GB_MEMBLOCK_ACC_WIDTH 10 * SIZE_SC
#define GPU_4GB_MEMBLOCK_ACC_HEIGHT 4

/*
 * ======================= GPU 6GB DIMENSIONS =======================
*/
#define GPU_6GB_DEPTH 20 * SIZE_SC
#define GPU_6GB_WIDTH 260
#define GPU_6GB_HEIGHT 6

#define GPU_6GB_BOARD_DEPTH 72 * SIZE_SC
#define GPU_6GB_BOARD_HEIGHT 6
#define GPU_6GB_BOARD_WIDTH 150 * SIZE_SC

#define GPU_6GB_CHIPSET_ACC_DEPTH 28 * SIZE_SC
#define GPU_6GB_CHIPSET_ACC_WIDTH 24 * SIZE_SC
#define GPU_6GB_CHIPSET_ACC_HEIGHT 6

#define GPU_6GB_MEMBLOCK_ACC_DEPTH 20 * SIZE_SC
#define GPU_6GB_MEMBLOCK_ACC_WIDTH 10 * SIZE_SC
#define GPU_6GB_MEMBLOCK_ACC_HEIGHT 4

/*
 * ======================= GPU 8GB DIMENSIONS =======================
*/
#define GPU_8GB_DEPTH 20 * SIZE_SC
#define GPU_8GB_WIDTH 260
#define GPU_8GB_HEIGHT 6

#define GPU_8GB_BOARD_DEPTH 72 * SIZE_SC
#define GPU_8GB_BOARD_HEIGHT 6
#define GPU_8GB_BOARD_WIDTH 150 * SIZE_SC

#define GPU_8GB_CHIPSET_ACC_DEPTH 28 * SIZE_SC
#define GPU_8GB_CHIPSET_ACC_WIDTH 24 * SIZE_SC
#define GPU_8GB_CHIPSET_ACC_HEIGHT 6

#define GPU_8GB_MEMBLOCK_ACC_DEPTH 20 * SIZE_SC
#define GPU_8GB_MEMBLOCK_ACC_WIDTH 10 * SIZE_SC
#define GPU_8GB_MEMBLOCK_2_ACC_WIDTH 5 * SIZE_SC
#define GPU_8GB_MEMBLOCK_ACC_HEIGHT 4

/*
 * ======================= GPU 16GB DIMENSIONS =======================
*/
#define GPU_16GB_DEPTH 20 * SIZE_SC
#define GPU_16GB_WIDTH 260
#define GPU_16GB_HEIGHT 6

#define GPU_16GB_BOARD_DEPTH 72 * SIZE_SC
#define GPU_16GB_BOARD_HEIGHT 6
#define GPU_16GB_BOARD_WIDTH 150 * SIZE_SC

#define GPU_16GB_CHIPSET_ACC_DEPTH 28 * SIZE_SC
#define GPU_16GB_CHIPSET_ACC_WIDTH 24 * SIZE_SC
#define GPU_16GB_CHIPSET_ACC_HEIGHT 6

#define GPU_16GB_MEMBLOCK_ACC_DEPTH 20 * SIZE_SC
#define GPU_16GB_MEMBLOCK_ACC_WIDTH 10 * SIZE_SC
#define GPU_16GB_MEMBLOCK_2_ACC_WIDTH 5 * SIZE_SC
#define GPU_16GB_MEMBLOCK_ACC_HEIGHT 4

/*
 * ======================= ATX COLORS =======================
*/

// Peripheria
#define ATX_MOTHERBOARD_COLOR 0, 128, 0 // green
#define ATX_MOTHERBOARD_COLOR_SHADOW 0, 100, 0 // dark green

#define ATX_HDMI_DP_COLOR 192, 192, 192 // silver
#define ATX_HDMI_DP_COLOR_SHADOW 128, 128, 128 // gray

#define ATX_BIOS_FLBK_COLOR 192, 192, 192 // silver
#define ATX_BIOS_FLBK_COLOR_SHADOW 128, 128, 128 // gray

#define ATX_U32G2_1_4_COLOR 192, 192, 192 // silver
#define ATX_U32G2_1_4_COLOR_SHADOW 128, 128, 128 // gray

#define ATX_LAN2_U32G2_56_COLOR 192, 192, 192 // silver
#define ATX_LAN2_U32G2_56_COLOR_SHADOW 128, 128, 128 // gray

#define ATX_U3252_C8_LAN1_U32G2_7_COLOR 192, 192, 192 // silver
#define ATX_U3252_C8_LAN1_U32G2_7_COLOR_SHADOW 128, 128, 128 // gray

#define ATX_M2_WIFI_COLOR 192, 192, 192 // silver
#define ATX_M2_WIFI_COLOR_SHADOW 128, 128, 128 // gray

#define ATX_AUDIO_COLOR 192, 192, 192 // silver
#define ATX_AUDIO_COLOR_SHADOW 128, 128, 128 // gray

// Processor socket
#define ATX_SOCKET_M4_COLOR 128, 128, 128 // gray
#define ATX_SOCKET_M4_COLOR_SHADOW 105, 105, 105 // dimgray

// RAM
#define ATX_DDR4_DIMM_B1_COLOR 0, 0, 255 // blue
#define ATX_DDR4_DIMM_B1_COLOR_SHADOW 0, 0, 139 // dark blue

#define ATX_DDR4_DIMM_B2_COLOR 255, 255, 0 // yellow
#define ATX_DDR4_DIMM_B2_COLOR_SHADOW 128, 128, 0 // olive

#define ATX_DDR4_DIMM_A1_COLOR 0, 0, 255 // blue
#define ATX_DDR4_DIMM_A1_COLOR_SHADOW 0, 0, 139 // dark blue

#define ATX_DDR4_DIMM_A2_COLOR 255, 255, 0 // yellow
#define ATX_DDR4_DIMM_A2_COLOR_SHADOW 128, 128, 0 // olive

#define ATX_PCIEX16_1_COLOR 240, 230, 140 // khaki
#define ATX_PCIEX16_1_COLOR_SHADOW 189, 183, 107 // dark khaki

#define ATX_PCIEX16_2_COLOR 240, 230, 140 // khaki
#define ATX_PCIEX16_2_COLOR_SHADOW 189, 183, 107 // dark khaki

#define ATX_PCIEX16_3_COLOR 240, 230, 140 // khaki
#define ATX_PCIEX16_3_COLOR_SHADOW 189, 183, 107 // dark khaki

/*
 * ======================= MICRO-ATX COLORS =======================
*/

// Peripheria
#define MICROATX_MOTHERBOARD_COLOR 0, 128, 0 // green
#define MICROATX_MOTHERBOARD_COLOR_SHADOW 0, 100, 0 // dark green

#define MICROATX_HDMI1_DP_COLOR 192, 192, 192 // silver
#define MICROATX_HDMI1_DP_COLOR_SHADOW 128, 128, 128 // gray

#define MICROATX_HDMI2_COLOR 192, 192, 192 // silver
#define MICROATX_HDMI2_COLOR_SHADOW 128, 128, 128 // gray

#define MICROATX_KBMS_USB_E32_COLOR 192, 192, 192 // silver
#define MICROATX_KBMS_USB_E32_COLOR_SHADOW 128, 128, 128 // gray

#define MICROATX_U32G2_C2_COLOR 192, 192, 192 // silver
#define MICROATX_U32G2_C2_COLOR_SHADOW 128, 128, 128 // gray

#define MICROATX_LAN_USB_E12_COLOR 192, 192, 192 // silver
#define MICROATX_LAN_USB_E12_COLOR_SHADOW 128, 128, 128 // gray

#define MICROATX_AUDIO_COLOR 192, 192, 192 // silver
#define MICROATX_AUDIO_COLOR_SHADOW 128, 128, 128 // gray

// Processor
#define MICROATX_LGA1200_COLOR 128, 128, 128 // gray
#define MICROATX_LGA1200_COLOR_SHADOW 105, 105, 105 // dimgray

// RAM
#define MICROATX_DDR4_DIMM_A1_COLOR 0, 0, 255 // blue
#define MICROATX_DDR4_DIMM_A1_COLOR_SHADOW 0, 0, 139 // dark blue

#define MICROATX_DDR4_DIMM_A2_COLOR 255, 255, 0 // yellow
#define MICROATX_DDR4_DIMM_A2_COLOR_SHADOW 128, 128, 0 // olive

#define MICROATX_DDR4_DIMM_B1_COLOR 0, 0, 255 // blue
#define MICROATX_DDR4_DIMM_B1_COLOR_SHADOW 0, 0, 139 // dark blue

#define MICROATX_DDR4_DIMM_B2_COLOR 255, 255, 0 // yellow
#define MICROATX_DDR4_DIMM_B2_COLOR_SHADOW 128, 128, 0 // olive

// GPU
#define MICROATX_PCIEX16_1_COLOR 240, 230, 140 // khaki
#define MICROATX_PCIEX16_1_COLOR_SHADOW 189, 183, 107 // dark khaki

#define MICROATX_PCIEX16_2_COLOR 240, 230, 140 // khaki
#define MICROATX_PCIEX16_2_COLOR_SHADOW 189, 183, 107 // dark khaki

/*
 * ======================= MINI-ITX COLORS =======================
*/

// Peripheria
#define MINIITX_MOTHERBOARD_COLOR 0, 128, 0 // green
#define MINIITX_MOTHERBOARD_COLOR_SHADOW 0, 100, 0 // dark green

#define MINIITX_USB3_5_COLOR 192, 192, 192 // silver
#define MINIITX_USB3_5_COLOR_SHADOW 128, 128, 128 // gray

#define MINIITX_USB7_10_COLOR 192, 192, 192 // silver
#define MINIITX_USB7_10_COLOR_SHADOW 128, 128, 128 // gray

#define MINIITX_HDMI_DP_COLOR 192, 192, 192 // silver
#define MINIITX_HDMI_DP_COLOR_SHADOW 128, 128, 128 // gray

#define MINIITX_LAN_USB3_34_COLOR 192, 192, 192 // silver
#define MINIITX_LAN_USB3_34_COLOR_SHADOW 128, 128, 128 // gray

#define MINIITX_M2_WIFI_COLOR 192, 192, 192 // silver
#define MINIITX_M2_WIFI_COLOR_SHADOW 128, 128, 128 // gray

#define MINIITX_AUDIO_COLOR 192, 192, 192 // silver
#define MINIITX_AUDIO_COLOR_SHADOW 128, 128, 128 // gray

// Processor
#define MINIITX_SOCKET_M4_COLOR 128, 128, 128 // gray
#define MINIITX_SOCKET_M4_COLOR_SHADOW 105, 105, 105 // dimgray

// RAM
#define MINIITX_DDR4_DIMM_A1_COLOR 0, 0, 255 // blue
#define MINIITX_DDR4_DIMM_A1_COLOR_SHADOW 0, 0, 139 // dark blue

#define MINIITX_DDR4_DIMM_B1_COLOR 255, 255, 0 // yellow
#define MINIITX_DDR4_DIMM_B1_COLOR_SHADOW 128, 128, 0 // olive

// GPU
#define MINIITX_PCIEX16_1_COLOR 230, 230, 140 // khaki
#define MINIITX_PCIEX16_1_COLOR_SHADOW 189, 183, 107 // dark khaki

#endif
